#!/usr/bin/env python3
"""mkmirror.py -- the byte Tennis reads one past the end of its score font.

$F527's `LDA ($B2),Y` runs with Y having reached $FF, so it reads
($B3:$B2) + $FF. In the stock image that is past the end of a 2K cartridge and
MAME folds it back through the mirror; in the FujiNet cartridge $1800-$1FFF is
the MAILBOX, so it lands on a text plane instead and the value becomes whatever
the boot bank last drew.

It is not decoration. The value lands in $8A, and $F396 and $F3AB use $8A to
clamp the range of return angles a racket can produce -- so the game depends on
it. Measured: with the planes left undriven the byte is $FF, the clamp never
fires, and `make det` runs 2384 frames identical; with them blanked it is $00,
the clamp fires on every return, and det diverges at frame 43.

THE ADDRESS IS A CONSTANT, and that is the whole reason this is one byte rather
than a table. $F14D is `SEC / LDA #$F6 / LDX #$06`, and the loop at $F154 walks
`STA $AC,X / SBC #$07` down X = 6,4,2,0 -- so $B2 is written with the literal
$F6 eight bytes before `JSR LF4EE`, on every frame, whatever the score. $B3 is
$F7 and stays $F7, because that loop writes only the low bytes.

So the read is $F7F6 + $FF = $F8F5, and the 2K fold is $F0F5. One byte.

The score-dependent pointer at $F04E does feed an EARLIER scoreboard pass whose
own Y = $FF read also lands out of range -- but that value is dead: nothing
reads $8A between the two passes, and the second overwrites it. `make glyph`
asserts the survivor is a single value across a run, which is the claim this
depends on.

Usage: mkmirror.py rom/tennis.bin > build/mirror.inc
"""
import sys

PTR = 0xF7F6                    # $B3:$B2, written as literals at $F14D
ADDR = ((PTR + 0xFF) & 0xF7FF)  # the 2K fold a stock cartridge performs


def main():
    rom = open(sys.argv[1], "rb").read()
    if len(rom) != 2048:
        sys.exit("mkmirror: expected a 2048-byte image, got %d" % len(rom))
    v = rom[ADDR - 0xF000]
    print("; generated by tools/mkmirror.py -- do not edit.")
    print("; $F7F6 + $FF = $%04X, which a 2K image folds to $%04X."
          % (PTR + 0xFF, ADDR))
    print("; See the tool for why this is one byte and not a table.")
    print("TNMIRRV EQU     $%02X" % v)


if __name__ == "__main__":
    main()
